//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuOtomasyonu.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class siparisler
    {
        public int siparisID { get; set; }
        public string musAdi { get; set; }
        public string musSoyadi { get; set; }
        public string Durum { get; set; }
        public string musAdres { get; set; }
        public string Tutar { get; set; }
    }
}
